### ISSUE TITLE
Undefined method "blank?" introduced as of 4.12.1, persists in 4.12.3

### ISSUE THREAD

**Issue by fdr** [aasm/aasm#508]
Hello,

I have a project that works perfectly with `4.12.0`, but when I upgrade aasm to `4.12.1`, `4.12.2`, or `4.12.3`, I receive stack traces complaining about `blank?` being undefined.

This is part of `activesupport` that is not `require`d by default. I can work around it by changing my gemfile to have this:

```ruby
gem 'activesupport', require: 'active_support/core_ext/object/blank'
```

But it does seem sub-ideal that AASM will crash out the gate otherwise.

**Comment by anilmaurya** [comment]
Hi @fdr ,

Can you provide full error trace and steps to reproduce this error ?

If you can provide a failing specs then it will help us resolve it sooner.

Thanks, Anil.

**Comment by fdr** [comment]
Sure. It is with any use of the `statename?` predicates:

```
NoMethodError: undefined method `blank?' for "running":String
```

```ruby
["/home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/persistence/base.rb:37:in `aasm_read_state'",
 "/home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/instance_base.rb:12:in `current_state'",
 "/home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aasm-4.12.3/lib/aasm/base.rb:103:in `block (2 levels) in state'",
 "(pry):1:in `<main>'",
]
```

**Comment by will** [comment]
@fdr did you ever find a solution for this?

**Comment by will** [comment]
I ran into this myself just now, and solved it by requiring the blank active support extension. The project I'm on does not use all of active support. It is not a rails project.

**Comment by anilmaurya** [comment]
@will @fdr Would you like to raise PR to resolve this issue ?

**Comment by tristandruyen** [comment]
FYI I made a PR which fixes this by using:
```
!thing || thing.empty?
```

instead of `thing.blank?`

**Comment by anilmaurya** [comment]
Released new version `5.0.5` which includes fix for this issue. Thanks to @tristandruyen .
