### ISSUE TITLE
Error when retrieving events from an instance with custom column name.

### ISSUE THREAD

**Issue by McRip** [aasm/aasm#195]
We have several aasm state machines in our project, but the only one failing in our project when checking instance level events is defined like this:

``` ruby
aasm :column => 'status', :skip_validation_on_save => true do
  ...
end
```

The test:

``` ruby
player.aasm.events.map(&:name)
```

The error and stacktrace:

```
NoMethodError: undefined method `to_sym' for false:FalseClass
gems/aasm-4.0.5/lib/aasm/persistence/base.rb:40:in `aasm_read_state'
gems/aasm-4.0.5/lib/aasm/instance_base.rb:11:in `current_state'
gems/aasm-4.0.5/lib/aasm/instance_base.rb:48:in `events'
player_spec.rb:31:in `block (3 levels) in <top (required)>'
```

All this works with 4.0.3 but is broken in 4.0.5

Thanks for your help.
